### ISSUE TITLE
How can I open a file in split buffer?

### ISSUE THREAD

**Issue by danielb2** [kien/ctrlp.vim#124]
I've highlighted a file and want to :sp on the file. If this isn't already possible, consider it a feature request :)

**Comment by kidphys** [comment]
Don't really want to create a separate issue for this. I run Vim with CtrlP in Window (Mysysgit), and Ctrl-X, Ctrl-T works fine, except Ctrl-V. I've checked :map and see that it's not mapped to anywhere else.

Any idea on how to resolve this?

**Comment by c9n** [comment]
@kidphys Do u solve your problem?

**Comment by wsdjeg** [comment]
please use this https://github.com/ctrlpvim

**Comment by kidphys** [comment]
@c9n I didn't, switched to Mac instead.
