### ISSUE TITLE
g:ctrlp_custom_ignore and hidden files/folders

### ISSUE THREAD

**Issue by obxhdx** [kien/ctrlp.vim#146]
I took a look at the related issues and none of them seemed to help.
Basically, I want to ignore hidden files and folders (e.g.: `.foo`). Therefore I'm doing the following:

```
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\..\+$',
  \ 'file': '\..\+$',
  \ 'link': '\..\+$',
  \ }
```

However, it has a side effect. Files like `foo.php` are also ignored. I couldn't manage to set it to ignore only matches with a leading `.`. If I add a `^` at the start of the pattern, it can't match anything, and as a result all (unwanted) hidden files start to appear again.

**Comment by ezmiller** [comment]
This is now `g:ctrlp_show_hidden`.
