### ISSUE TITLE
Make Ctrl-t default behavior

### ISSUE THREAD

**Issue by sdhull** [kien/ctrlp.vim#160]
In my workflow, I like to keep tabs open of files I'm working on. This means when I want to open a new file, I almost _always_ want it to open in a new tab.  When I have too many tabs open, I _love_ the functionality of switching back to a tab for a file I already have open.  So ctrl-t is now my favorite way to open files with Ctrl-P, but it feels awkward.

Is there any way to make Ctrl-t the default behavior when I just want to open files with "return"?

**Comment by jlgasparrini** [comment]
Good Joob!! :+1:

**Comment by jlgasparrini** [comment]
For this behaviour! When we seek and open the first file with ctrl-p, Is there any way (with default settings) to remove the empty tab? (This empty tab is created by vim, when this is opened)
![a little clearer](https://cloud.githubusercontent.com/assets/4787484/10310718/bf6d9cd8-6c19-11e5-8ca1-240dea42bed5.png)

**Comment by sivaswami** [comment]
:heart: this option

**Comment by runekaagaard** [comment]
The remapping don't seem to work with nerdtree. When nerdtree is open while I press enter in ctrlp it replaces nerdtree instead of creating a new tab. It works fine with ctrl+t.

**Comment by runekaagaard** [comment]
I made it work with nerdtree and the powerline tabline by adding this to my .vimrc:

    let g:ctrlp_open_func = { 'files': 'CustomOpenFunc' }
    function! CustomOpenFunc(action, line)
        call call('ctrlp#acceptfile', [':t', a:line])
    endfunction

**Comment by acidjazz** [comment]
@kien  I think this is definitely something that should be in the readme, everyone has their preference of how they open files and I think this really helps w/ that, if you want I'll write it up and submit a PR if you don't have the time.
