### ISSUE TITLE
Ignore files in .gitignore

### ISSUE THREAD

**Issue by wolverian** [kien/ctrlp.vim#174]
It'd be nice if ctrlp automatically ignored files listed in .gitignore, and even better if it supported the whole .gitignore syntax. Same goes for other VCSs, of course.

The alternative of using 'git ls-files' as the glob function is problematic because:
- the documentation doesn't tell you how to configure it on Windows, and
- the directory might have files not yet tracked by the VCS.

**Comment by pgilad** [comment]
Works great!

**Comment by marcelolima** [comment]
Thanks a lot @dhinus! worked like a charm

**Comment by pklingem** [comment]
lWorks great for me as well.  Much better than duplicating all of those ignores in something like:

    let g:ctrlp_custom_ignore = {
      \ 'dir':  '\v[\/](doc|tmp|node_modules)',
      \ 'file': '\v\.(exe|so|dll)$',
      \ }

**Comment by faceleg** [comment]
@kien can we have @dhinus' comment included in the readme? This made CTRLP infinitely more usable for me

**Comment by rafaelrinaldi** [comment]
@dhinus This is exactly what I was looking for. Thanks for sharing.

**Comment by fibo** [comment]
@dhinus nice snippet, I just tryed it in neovim and works like a charm.

**Comment by oblitum** [comment]
@dhinus hi, this is great, but if I start vim inside a subdirectory of the repository the command shows nothing and err because `.git/` is missing.

**Comment by oblitum** [comment]
From http://kien.github.io/ctrlp.vim/, this is better and fix the previous:

``` vim
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
```

**Comment by tim-phillips** [comment]
I wanted to use the above `git ls-files` command along with a second command to ignore more file names. Turns out we can't use `g:ctrlp_custom_ignore` with `g:ctrlp_user_command`, and using multiple `types` within `g:ctrlp_user_command` is OR rather than AND. So I'm using the following in my `.vimrc`:

```
if executable('ag')
  " Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
  set grepprg=ag\ --nogroup\ --nocolor
  " Use ag in CtrlP for listing files. Lightning fast, respects .gitignore
  " and .agignore. Ignores hidden files by default.
  let g:ctrlp_user_command = 'ag %s -l --nocolor -f -g ""'
else
  "ctrl+p ignore files in .gitignore
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
endif
```

https://stackoverflow.com/questions/24479101/vim-ctrlp-not-parsing-ag-silver-search-ignore-option-correctly

**Comment by mightyiam** [comment]
It seems that the recommended `ctrlp_user_command` (in the readme) just works, right?

Perhaps make it a little more robust by falling back to default somehow, in case there is no `git` command, and making it a default?

Seems sane to me.

**Comment by OskarSigvardsson** [comment]
Just adding my two cents here, I wanted CtrlP to ignore all binary files as well as the stuff in my gitignore, which the `git ls-files` version doesn't do. I happen to have [ripgrep](https://github.com/BurntSushi/ripgrep) installed, so this version works great for me: 

    let g:ctrlp_user_command = ['.git', 'cd %s && rg --files-with-matches ".*"', 'find %s -type f']

The idea is that ripgrep respects .gitignore and doesn't search binary files. If you add the --files-with-matches flag, it just lists the files with matches, so if you search for `.*` (i.e. regex-speak for "anything"), it will just list all text files in your repo. Very handy, and extremely fast. I suspect you could coerce `git grep` into doing something similar.

**Comment by rafaelrinaldi** [comment]
@OskarSigvardsson That's great, thanks for sharing. Also, you can replace `&&` by simply `;` so it works seamlessly in fish too 👍

**Comment by hulloanson** [comment]
A question on this:
```vim
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
```

Doesn't this include deleted but git-cached files?

**Comment by hulloanson** [comment]
Personally I find 

```vim
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -c --exclude-standard --recurse-submodules | grep -x -v "$( git ls-files -d --exclude-standard )" ; git ls-files -o --exclude-standard', 'find %s -type f' ]
```

to be more acceptable. Not sure if this is fool-proof but I haven't seen any problem yet. (It was a personal preference to `--recurse-submodules`)
