### ISSUE TITLE
Paste doesn't work in the ctrlp prompt

### ISSUE THREAD

**Issue by ramn** [kien/ctrlp.vim#176]
It seems I can't paste from clipboard in the ctrlp prompt, with middle mouse button for instance.

**Comment by tanwangzugata** [comment]
if you have the absolute path or relative to Vim's `pwd` path of a file, you can also do:

`:drop (paste)`
`:find (paste)`
`:tabfind (paste)`
`:sfind (paste)`
`:vert sfind (paste)`
