### ISSUE TITLE
Sort order of results

### ISSUE THREAD

**Issue by mwilden** [kien/ctrlp.vim#177]
How does CtrlP sort its results in mru-files mode? For example, I work a lot with app/assets/stylesheets/widgets/jquery.antcat.reference_picker.sass. However, when I type sass in CtrlP's prompt (in either file or directory mode), that file always appears at the TOP of the list. At the bottom of the list are much shorter filenames that I haven't edited in weeks.

**Comment by naught101** [comment]
Hrm... How is this supposed to work? I have 

```
let g:ctrlp_mruf_default_order = 1
```

in my .vimrc, and still if I `<c-p>` and select `R/PLUMBER_plot.R`, then `<c-p>` and select `R/PLUMBER.R`, and then `<c-p>pl`, then the first thing that comes up is `R/all_plots.R` (`PLUMBER_plot.R` is third up the list). Am I missing something?

**Comment by naught101** [comment]
Ah, I think I was misunderstanding how CtrlP works - didn't realise there were separate buffer and file lists. Feature request for what I'm talking about here: https://github.com/kien/ctrlp.vim/issues/659
