### ISSUE TITLE
Can't use Arrow Keys

### ISSUE THREAD

**Issue by eipark** [kien/ctrlp.vim#209]
I used to use the arrow keys when finding a file. Say, I'd type a few letters, see what i wanted was two files up from the currently selected one, so I'd hit up twice and enter to get to my file. Now hitting the arrow keys exits ctrl-p. I imagine this is a config error on my part though.

**Comment by embray** [comment]
FWIW I encountered the same issue using CtrlP in Windows--had to add "cygwin" in `MapSpecs`.

**Comment by ghost** [comment]
I had this problem when using putty and with TERM set to putty-256color. After changing it to xterm-256color it worked fine.
