### ISSUE TITLE
Ignored files show up in results

### ISSUE THREAD

**Issue by mrinterweb** [kien/ctrlp.vim#220]
I have the following set in my .vimrc

```
set runtimepath^=~/.vim/bundle/ctrlp.vim
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.jpg,*.gif,*.png,*.pdf
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.hg$\|\.svn$',
  \ 'file': '\.png$\|\.gif$\|\.jpg$',
  \ }
```

Files ending with jpg, gif, pnd, ... etc keep showing up in the result list. I thought these settings were supposed to help eliminate unwanted files from showing up in the results.

**Comment by alecdwm** [comment]
For future reference, if someone wanted to keep their `ctrlp_user_command` but still take advantage of vim's `wildignore` option, they could modify @allantokuda's example to look like the following:

	let g:ctrlp_user_command = {
	\	'types': {
	\		1: ['find %s -type f'],
	\	},
	\	'ignore': 1,
	\}

However, it is noted in the docs that this can significantly reduce the performance benefits of using an external program (e.g. `ag`) in the first place.
