### ISSUE TITLE
scrollable result window?

### ISSUE THREAD

**Issue by jeroendv** [kien/ctrlp.vim#227]
When entering a search querry is there some kind of indication that the list of files that is shown is only a subset of al the files that match the querry?

If the number of matching files is less then the max height then the window will shrink accordingly.
However, if the number of matching files is more then the max height, then the window height is simply capped and  there does not seems to some kind of indication that there are more matches than the ones that are shown in the window. 
Further more the window also can't be scrolled. I.e. pressing <C-K> will not scroll the window up and reveal other files that match the query.

Am I correct in this assessment?

with kind regards

**Comment by woto** [comment]
Also view https://github.com/kien/ctrlp.vim/issues/449 it allow to scroll results
