### ISSUE TITLE
Does not find all files

### ISSUE THREAD

**Issue by jjasonclark** [kien/ctrlp.vim#234]
I've installed the plugin but I cannot find all files in my project.

I'm in a rails project looking for a nested file in test/no_rails/unit/lib/export/entertainment/item_grouper_test.rb. I thought this might be caused by a file number limit. The Command-T plugin needed me to increase the limit to see this file. So I did :let g:ctrlp_max_files=20000 and :let g:ctrlp_custom_ignore='.git$|\tmp$' in order to try to increase the limit and reduce unused files. This didn't work.

I can open the file manually and then use the :CtrlPMixed command to find the file like normal.

What else can I do to find the file without first manually opening it?

**Comment by mooreniemi** [comment]
`let g:ctrlp_max_files=0` worked for me!

**Comment by w2moon** [comment]
It cannot found the file in a git repo's submodule unless i enter the folder of the submodule first.

**Comment by wsdjeg** [comment]
@w2moon what is out put of git ls-files in terminal in your root directory

**Comment by wsdjeg** [comment]
if you have set use_command = git ls-files
it will not show the files in sub repo
and also only show the files you have added
use this command to add all the files `git add .`

**Comment by berkos** [comment]
`let g:ctrlp_max_files=0` worked for me too. Thanks

**Comment by iovanom** [comment]
I add

```
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40
```

and worked for me. Thanks.

**Comment by jponc** [comment]
`let g:ctrlp_max_files=0` worked as well, thanks!

**Comment by arturmalecki** [comment]
My project has 47404 files 😱 and without:

```
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40
```

ctrlp didn't work correctly.

Thanks!

**Comment by butterywombat** [comment]
thanks so much~ it was driving me crazy figuring out why my ctrl p suddenly broke

**Comment by ggalindezb** [comment]
@screwzm NAILED IT! Thanks man. I love you. No homo.

**Comment by rryk** [comment]
Same here. I've searched in my home dir with lots of projects and over 1 million files, so without 

```
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=100
```

Ctrl+P didn't find all of them.

**Comment by skylarmb** [comment]
For me the issue was the files were not added to git. I have a custom user_command

```
let g:ctrlp_user_command = {
  \ 'types': {
    \ 1: ['.git', 'cd %s && git ls-files'],
    \ 2: ['.hg', 'hg --cwd %s locate -I .'],
    \ },
  \ 'fallback': 'find %s -type f'
\ }
```

After running `git add .` and clearing cache they show up. 👍

**Comment by gamato** [comment]
Perhaps Ctrl-P could/should warn a user when it reaches ctrlp_max_files limit and not all files have been found yet.

**Comment by TPei** [comment]
In my case `let g:ctrlp_max_files=0` made ctrl-p basically unusable. Since the default is 10000 you might want to play around with increasing that. For me `let g:ctrlp_max_files=15000` was enough to find all files and still be usable.

See also https://github.com/kien/ctrlp.vim/issues/163
