### ISSUE TITLE
One-off equivalent to g:ctrlp_user_command

### ISSUE THREAD

**Issue by tpope** [kien/ctrlp.vim#273]
Here's my current `ctrp_user_command`:

```
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
```

For a while now, I've been wanting to make some form of this accessible from Fugitive, but I've been stumped as to how to do it uninvasively. Clobbering `g:ctrlp_user_command` would of course be the height of rudeness. Even if I could figure out how to carefully mutate it, that's still potentially frustrating a user who depends on the existing behavior.

Today, as I was experimenting with giving the buffer that `:Gstatus` creates a larger role, one solution came to me. What if I could activate this behavior only in said buffer? Surely nobody would find that offensive. In fact, the existing `<C-p>` is obliviously clobbered, and nobody has complained, so this seems like to perfect sandbox to experiment in.

Best I can tell, though, there's no external API that lets me accomplish this, so I am requesting that you add one. The absolute perfect interface (allowing maximum flexibility for things like submodules, with their weird Git dir), would be a way to tell ctrlp.vim "use these files and consider them relative to that directory". For example:

```
let files = split(system('git --git-dir=/tmp/repo/.git/modules/submodule ls-files -oc --exclude-standard'), "\n")
call ctrlp#custom({'root': '/tmp/repo/submodule',  'files': files})
```

But don't let me tell you how to design your own interface. I'm sure I can make use of whatever bone you throw me.

**Comment by elsonwu** [comment]
@Alvan told me, below command would work much better:

```
" When you have ignore files like this below
let g:ctrlp_custom_ignore = {
            \ 'file': '\.(pkg|dmg|exe|so|dll|pyc|pdf|jpg|jpeg|png|gif|bmp|gz|zip|rar)$',
            \ }

if executable('git')
    let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard' .
                \ (exists('g:ctrlp_custom_ignore') && has_key(g:ctrlp_custom_ignore, 'file') ? 
                    \ ' | grep -v -E "'. g:ctrlp_custom_ignore['file'] .'"' :
                    \ '' )
                \ ]
en
```
