### ISSUE TITLE
Feature Request: Delete Buffer in CtrlPBuf Mode

### ISSUE THREAD

**Issue by amadeus** [kien/ctrlp.vim#280]
I searched through the documentation but I couldn't find it anywhere...

I tend to be pretty anal about my buffer management and thought it would be nice to press &lt;c-d&gt; and delete the currently selected buffer in the list (and keep the buffer list open).

Thoughts?

**Comment by j5shi** [comment]
+1, please, add it to ctrlp or accept a pull request for it.

**Comment by bravoecho** [comment]
@kien 
I've added this to the bouncing-vim distro with a key combo that works also in tmux and mimics the line deletion already provided by the plugin (https://github.com/lucabelmondo/bouncing-vim/commit/4e296557288a38c128ba714bebc059a57389509e) but I would like to  +1 :grinning:

**Comment by zQueal** [comment]
@j5shi Thanks for the PR. Just added it to my Vim install on Windows. Working great.
