### ISSUE TITLE
Can't find files (multiple nested directories)

### ISSUE THREAD

**Issue by ajankovic** [kien/ctrlp.vim#284]
**Note:** This is not a cache issue, I cleared cache multiple times.

I am developing in Magento. And it has weird number of nested directory levels.

In this concrete example:
**app\design\frontend\enterprise\compexV2\layout**  <-- This path is cached and searchable
**app\design\frontend\enterprise\compexV2\template** <-- This path and all files and directories underneath it are not cached and search string yields no result. 

Example input:
**"apcompexV2t"** <-- Lists all results only for "layout" directory (like it caches "t" as the last letter of "layout")
With **"appenterpricompexV2temp"** i get no results at all.

Is there some limit to the level of directories that are being cached? Or is this issue related to something else?

I am currently working on Windows 7 machine but will soon check this on my Linux box also.

**Comment by pBlasiak** [comment]
Hi
I found that if I have dir named via only capital letters (e.g. MYDIRECTORY)
ctrlp can't find my files
how can I solve it?

**Comment by pBlasiak** [comment]
Hi
I found that if I have dir named via only capital letters (e.g. MYDIRECTORY)
ctrlp can't find my files
how can I solve it?

**Comment by pBlasiak** [comment]
no sorry
when I changed the name to lower case it still cannot find file
I am attaching folder structure
I want to find a file MULES.H which is located in
src/finiteVolume/fvMatrices/solvers/MULES directory
my settings are
let g:ctrlp_working_path_mode = 'rw'
"let g:ctrlp_working_path_mode = 'ra' 
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=1000
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
[src.tar.gz](https://github.com/kien/ctrlp.vim/files/2231648/src.tar.gz)
