### ISSUE TITLE
Auto refresh cache when filesystem changes

### ISSUE THREAD

**Issue by docwhat** [kien/ctrlp.vim#305]
It'd be really helpful if CtrlP could auto-refresh when the filesystem changes. Especially since Linux and OS X both have really nice libraries for detecting filesystem changes.

I have no idea how something like that would work... :-/

Ciao!

**Comment by moeabdol** [comment]
+1 @docwhat works like a charm. Thanks.

**Comment by hakunin** [comment]
A few scenarios where it would be nice to be able to auto clear:
1) I'm adding a new file
2) I'm renaming a file
3) I switched branches

Switching branches is the most painful one and all the cases could be covered if you check what `git status` says before I run CtrlP.

It would work nicely for git repos and no additional dependencies are required.
