### ISSUE TITLE
Ctrl-P excludes folders

### ISSUE THREAD

**Issue by MattNguyen** [kien/ctrlp.vim#313]
When I run ctrl-p in my Rails projects, ctrl-p completely ignores my apps and specs folder. I've cleared my cache, but to no avail. Not sure what other information I should provide to you, so please point me in the right direction.

**Comment by Supernats** [comment]
@rizzatti I should have read that section long ago. Such a wonderful tip. Thanks!

**Comment by savroff** [comment]
@rizzatti you just saved my ass 👍
