### ISSUE TITLE
Change the color of the selected line

### ISSUE THREAD

**Issue by marlun** [kien/ctrlp.vim#337]
Hi,

Only writing this as an issue because I couldn't find any other way to ask this question.

Is it possible to change the color of the selected line which will be opened if I hit enter? RIght now it's just a lighter gray and I'd like to make it stand out more.

I've looked at :h ctrlp-customization but couldn't find what I wanted.

**Comment by silesky** [comment]
I wanted a bright cursorline in ctrlp, but not in my day-to-day editing. It's as simple as this:

```
hi cursorline cterm=none ctermbg=darkred ctermfg=white guibg=darkred guifg=white
set nocursorline
```

**Comment by paulsc** [comment]
@bryankennedy did you ever figure out how to do this without also changing the cursorline color of your regular editing window ? I can't seem to crack it.
