### ISSUE TITLE
feature request: live preview on current match

### ISSUE THREAD

**Issue by bling** [kien/ctrlp.vim#350]
Sublime has a similar feature with it's Ctrl/Cmd+P search, where the current best match will actually be opened and displayed in the background.

Presumably you could do the same thing in Vim (either using the main window, or with :pedit).  And as the match is refined probably a good idea to :bd the old matches.

**Comment by lucagiovagnoli** [comment]
++ this would be a very sweet option

**Comment by danrasmuson** [comment]
+1 Any update on this?

**Comment by rleger** [comment]
+1

**Comment by htatche** [comment]
+1

**Comment by UncleGoogle** [comment]
+1 ones can use the vim 'preview window'

**Comment by crivotz** [comment]
+1, good option

**Comment by j5shi** [comment]
+1

**Comment by githorse** [comment]
+1

**Comment by HendrikPetertje** [comment]
Actually a thing in FZF already.. Just run:

```
call fzf#vim#files('', fzf#vim#with_preview('right'))
```

Would love to see this in ctrlp ;)

**Comment by rleger** [comment]
You can even set the width and position of the preview window

```
:call fzf#vim#files('', fzf#vim#with_preview('right:60%'))
```

**Comment by dmitriyK1** [comment]
+1

**Comment by elrok123** [comment]
+1 please add this, it would make ctrlp almost perfect! Super handy instead of constantly hitting return and going back to ctrlp to resume your search. Make it flawless!

**Comment by Marvin182** [comment]
+1

**Comment by MartinezCatriel** [comment]
+1 🙏

**Comment by elrok123** [comment]
+1

**Comment by dominikduda** [comment]
+1

**Comment by bartoszmaka** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by milushov** [comment]
https://github.com/junegunn/fzf.vim guys

**Comment by bling** [comment]
closing, as development has moved to the active fork https://github.com/ctrlpvim/ctrlp.vim. please continue the discussion at https://github.com/ctrlpvim/ctrlp.vim/issues/508
