### ISSUE TITLE
Navigating file list without using arrow keys

### ISSUE THREAD

**Issue by jithine** [kien/ctrlp.vim#360]
One of the great ways of using vim is to be able to type without having fingers moving to arrow keys. Though I love this plugin, I find that it forces me to use arrow keys to navigate matched files list.
Can this be enhanced so that navigation can be done with out using arrow keys?

**Comment by damienjbyrne** [comment]
Don't feel bad @jithin1987, four years later and I had to google this issue to find the obvious too.  :-)
