### ISSUE TITLE
Configure window display at TOP or BOTTOM

### ISSUE THREAD

**Issue by emancu** [kien/ctrlp.vim#392]
`CommandT` has a simply option to do it
`let g:CommandTMatchWindowAtTop = 1`

Edit: 
Here we have `let g:ctrlp_match_window_bottom = 0` sorry I miss that option from the help.

**Comment by nchase** [comment]
yes! see the `g:ctrlp_match_window` configuration and add to your vimrc, e.g. `let g:ctrlp_match_window = 'order:ttb'`
