### ISSUE TITLE
`g:ctrlp_working_path_mode` wording hard to understand

### ISSUE THREAD

**Issue by flavius** [kien/ctrlp.vim#397]
I think the following is difficult to understand:

>  'a' - like 'c', but only applies when the current working directory outside of CtrlP isn't a direct ancestor of the directory of the current file.

We were a little puzzled about it on #vim @ freenode too. Could you please add a succint relevant information on the homepage [1], to make it clear and quick to understand?

[1] http://kien.github.io/ctrlp.vim/

**Comment by bradwood** [comment]
I don't understand this wording either...  Maybe a picture would help? 😕
