### ISSUE TITLE
Need explanation of status line

### ISSUE THREAD

**Issue by lsiden** [kien/ctrlp.vim#401]
In the docs, I'd like to see an explanation of the status line.  What does "prt" mean.  What does "<buf>={ mru files }=<fil> <->", etc.  mean?  It looks like the highlighted one between the curly braces might be the current mode, but what do the ones between the angular braces mean and why do they change places when they're toggled?

**Comment by zhuweifeng314** [comment]
Kind of figured out the meanings ( just my understanding ). 

prt: indicates that the focus is on the prompt, not on the match window. When you use `<s-tab>` ( shift + tab ) to change the focus to the match window, `prt` will be `win` ( which indicates match window ).

`<->`: when you use `<c-z>` to mark item in the match window, `<->` will display the number of items you marked.
