### ISSUE TITLE
Replacing a.vim functionality with ctrlp.vim

### ISSUE THREAD

**Issue by SirVer** [kien/ctrlp.vim#412]
Thanks for making CtrlP! It has replaced FuzzyFinder on my systems and I had 0 issues with it so far. Very impressive! I did not know where to post this as it is not really a issue, more a request for help or documentation pointer.

I am using a very old vim script http://www.vim.org/scripts/script.php?script_id=31 to switch between paired files. Namely in a blah.cc file, using :A will open blah.h file in the same folder and vice versa. This is immensely useful, but unfortunately it fails if the header is in another directory.

I thought it would be possible to use ctrlp for this programmatically, but failed miserably. What I want to achieve is essentially this algorithm when :A is called:
- find %:t and change the extension (if .cc -> .h and vice versa)
- call CtrlP ., enter in the string found in the last step
- press return (open first match, alla I'm feeling lucky).

I messed around with feedkey() and tried to understand if I can hook into cltrp in any other way, but failed miserably. Any ideas?

**Comment by iliis** [comment]
Based on above suggestions I'm currently using

```vim
function! SwitchHeader(split)
    let g:ctrlp_default_input = expand('%:t:r')
    call ctrlp#init(0)
    if a:split == 'horizontal'
        call feedkeys("\<c-x>", "t")
    elseif a:split == 'vertical'
        call feedkeys("\<c-v>", "t")
    else
        call feedkeys("\<cr>", "t")
    endif
    unlet g:ctrlp_default_input
endfunction

map <F11> :call SwitchHeader('')<CR>
map <S-F11> :call SwitchHeader('horizontal')<CR>
```

This switches immediately (no need to press enter) without being sluggish.
