### ISSUE TITLE
Hiding the statusline altogether

### ISSUE THREAD

**Issue by cesarfigueroa** [kien/ctrlp.vim#413]
Is there a way to do this? I have no need for it.

**Comment by manasthakur** [comment]
For me, the solution posted above works fine (I am not getting any statusline after that). However, considering that this is an older post, is there a simpler solution now?

**Comment by openjck** [comment]
What's the point of the statusbar, anyway? Like @cesarfigueroa I always see the same cryptic text. I'm new to ctrlp so I'm probably just missing something.
