### ISSUE TITLE
E21: Cannot make changes, 'modifiable' is off - Can't type ⌘V to paste text to the search in MacVim.

### ISSUE THREAD

**Issue by hobbes3** [kien/ctrlp.vim#419]
I can't paste text to search when I type either ⌘V or paste from the menu in MacVim. Vim gives the following error:

```
E21: Cannot make changes, 'modifiable' is off
```

But I _can_ paste text to Ctrlp when I use `vi` in my Terminal.

I installed MacVim using `brew install macvim`, but first modified the formula to compile against homebrew's Python (2.7.5) instead of system python (2.7.2).

I installed Ctrlp using Vundle and here is my Ctrlp settings in my `.vimrc`

```
" Remap the default <c-p>.
let g:ctrlp_map = '<Leader>]'
let g:ctrlp_max_height = 20
let g:ctrlp_show_hidden = 1

" Ignore files and folders.
let g:ctrlp_custom_ignore = {
\ 'dir':  '\v[\/](\.(git|hg|svn|Trash)|Applications|Downloads|Games|Library|Movies|Music|Pictures|pytz\/zoneinfo)$',
\ 'file': '\v(tags|\.(exe|so|dll|wav|mp3|mo|DS_Store|svn|png|jpe?g|jpg\.mno|gif|elc|rbc|pyc|swp|psd|ai|pdf|mov|aep|dmg|tar|zip|gz|shx|shp|wmf||bmp|ico|avi|docx?|xlsx?|pptx?|upart|ipa))$',
\ 'link': '\v\.__INCLUDE_VERSION__$',
\}
```

**Comment by cdalsass** [comment]
Hi @hobbes3, could you explain in more detail what you did? You're message is a bit abbreviated.
Thanks!
Charlie
