### ISSUE TITLE
Use j, k instead of <c-j>, <c-k>

### ISSUE THREAD

**Issue by dbarros** [kien/ctrlp.vim#422]
I was curious as to why j and k aren't used to move up and down the list of matching files, instead of the current ctrl-j and ctrl-k? To me, I would like to stay in the state of using j, k (which is normal for vim) to do the movement.

Like I say, just curious as to why it's like this.

Thanks, love the pluigin.

**Comment by duleorlovic** [comment]
Just for reference, here is what I have in my `.vimrc` so `ctrl+j` open selected file in current buffer
~~~
" make ctrl-o immediatelly replace buffer so we don't need to answer OpenMulti prompt
" Open Selected: [t]ab/[v]ertical/[h]orizontal/[r]eplace/h[i]dden? 
let g:ctrlp_prompt_mappings = {
\ 'PrtSelectMove("j")':   ['<down>'],
\ 'AcceptSelection("r")': ['<c-j>'],
\ }
~~~
