### ISSUE TITLE
Can't get F5 to work

### ISSUE THREAD

**Issue by lsiden** [kien/ctrlp.vim#428]
Despite other ctrlp features and mappings working flawlessly, I can't get F5 (PrtClearCache) to work.  When I hit func key F5 in ctrlp mode, it just exits back to whatever buffer I was in.  Old, defunct files are still in MRU list.

I ran ggrep -R (Solaris) on ~/.vim/ to see if it was getting unmapped in some script, but that's not the case.  Only the ctrlp bundle references F5.

In autoload/ctrlp.vim I tried changing line 138 to
    \ 'PrtClearCache()':   ['<S-F5>'], 

Now when I hit shift-F5 in ctrp mode, it switches to the buffer help.txt and when I hit F5 alone, it switches back to whatever buffer I was in, but with the modified flag set, as if I had just run some edit command.

How else can I debug this?  I'm a programmer and long-time vim user, but no experience with vim scripts (as yet).

**Comment by snamoah** [comment]
I got my <F5> to work in my vim in iTerm2 by setting `term=screen-256color` instead of `term=builtin-ansi` in .vimrc

See explanation here http://vim.wikia.com/wiki/Turn_on_syntax_coloring_in_Mac_OS_X
NB: using macos high sierra
