### ISSUE TITLE
Q: highlight matched chars when matched type is 'line'

### ISSUE THREAD

**Issue by tacahiroy** [kien/ctrlp.vim#431]
Thanks for a great plugin.

This is just a question (and request, actually).
Currently, ctrlp.vim does highlight matched chars when its extension type is 'path'.

Why does the feature work only with 'path' type extension?
I think it's not a problem ctrlp.vim highlight matched chars if an extension type is not 'path'.

What do you think about it?
Thanks,
/T

**Comment by dragonxlwang** [comment]
hope this thread is not buried yet. is this feature scheduled to be done any soon? Thanks,
