### ISSUE TITLE
Delete the preceding character slowly

### ISSUE THREAD

**Issue by Fulun** [kien/ctrlp.vim#492]
I'm working for a large project on unix. I always use ctags to generate the tag file.When using Ctrlp to search for specific tag and making typical spelling mistakes, I find that it will take about 1 second to delete every preceding character. This is more than I can tolerate.So I have to use Ctrl+u to clear the input field and type correctly.
Is there some setting I could set to avoid this issue?
My vim version is: 7.0.237

Look forward to your reply
Thanks!

**Comment by jbodah** [comment]
> Natively, you can try g:ctrlp_lazy_update which should alleviate it somewhat

Works great, thanks!

**Comment by j5shi** [comment]
> Natively, you can try g:ctrlp_lazy_update which should alleviate it somewhat

Works like a charm!
