### ISSUE TITLE
Files stuck in cache, intended behavior?

### ISSUE THREAD

**Issue by kswope** [kien/ctrlp.vim#523]
.vimrc

```
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_working_path_mode = 0
```

shell

```
rm -rf .cache/ctrlp/
mkdir ctrlp-test
```

vim

```
:cd ~/ctrlp-test/ 
<ctrl-p>
== NO ENTRIES ==
```

<i>Great!</i>

shell

```
touch ~/ctrlp-test/HERE-1
touch ~/ctrlp-test/HERE-2
```

vim

```
<ctrl-p>
<F5>

HERE-1
>HERE-2
```

<i>Great!</i>

shell

```
rm ~/ctrlp-test/HERE-2
```

vim

```
<ctrl-p>
<F5>

>HERE-1
```

<i>Great!</i>

vim

```
:e /etc/hosts
:bd
<ctrl-p>
<F5>

/etc/hosts
>HERE-1
```

<i>/etc/hosts lingers!</i>

shell

```
rm ~/ctrlp-test/HERE-2
```

vim

```
<ctrl-p>
<F5>

/etc/hosts
```

<i>its like a bad smell that wont go away!</i>

vim

```
:CtrlPClearAllCaches 
<ctrl-p>
<F5>

/etc/hosts
```

I would expect <F5> to rebuild the cache according to ctrlp_working_path_mode
and not leave files in the cache outside the 'ctrlp working path'.

I also tried

```
let g:ctrlp_working_path_mode = 'c'
```

**Comment by jgandt** [comment]
I thought I would mention here that the `ctrlp_mruf_relative` option has been added. I came to this issue via a top google result and thought it important to share my findings. It solves an issue very close to what OP is describing.

Documentation here: https://github.com/kien/ctrlp.vim/blob/1.79/doc/ctrlp.txt#L75
