### ISSUE TITLE
Newly created files not showing in currently running vim session when i do ctrl-p

### ISSUE THREAD

**Issue by ghost** [kien/ctrlp.vim#525]
Im using Ctrl-P in vim version 7.4 on my mac machine running osx mountain lion. I noticed that new files i create from terminal or from within vim , dont show up when i do ctrl-p from within a currently running vim session. If i quit and restart vim then the files show up in ctrl-p. Is this a bug or some problem with my setup ?

Please help
Thanks

**Comment by hakunin** [comment]
Btw why can't we just have the new files (that I save for the first time in project directory) show in ctrlp without any refresh? Seems like it could be just added to the cache once I create a new file.

**Comment by razasayed** [comment]
@hakunin :+1:

**Comment by wsdjeg** [comment]
@hakunin @razasayed please use this active fork 
https://github.com/ctrlpvim/ctrlp.vim
when create an new file,maybe it can not be added ,because most git user,use git ls-files as ctrlp command,this only shows the file that has been added into repo.

**Comment by razasayed** [comment]
Thanks @wsdjeg for pointing this out.
