### ISSUE TITLE
How can I manually set ctrlp's directory to search on a per project basis?

### ISSUE THREAD

**Issue by BeekeeperAlex** [kien/ctrlp.vim#526]
At work I have a "work-code" folder in my home directory. Within that directory there are about five git repositories that are all related. I love how ctrlp travels the directory tree until it finds a .git folder to use as reference. However, in this case I want ctrlp to jump up one directory to "work-code" and search all five of my repositories.

I know that can disable ctrlp's feature to traverse the directory tree looking for .git but I don't want to disable it. I just want to manually specify the ctrlp directory but only in those five projects. Is there a way to tell ctrlp what base directory to use on a per project basis?

**Comment by othane** [comment]
It would be really good if you could add directories to scan like you do with tags, ie set ctrlp_search_dir+=~/work/blah ... I was looking to see if this was possible with the current code, but I cannot find any options for this. Could this be a new feature that is need?

**Comment by domi91c** [comment]
Could a variable be set with some other mapping which can then be used with `let g:ctrlp_root_directory = PROJECT_ROOT`? I don't know Vimscript ;_;

**Comment by domi91c** [comment]
Sweet, this works: `let g:ctrlp_root_markers = ['.ctrlp']`

https://coderwall.com/p/5xv7sq/ctrlp-root-markers

**Comment by CookiesBestDinner** [comment]
g:ctrlp_root_markers is handy for limiting to a sub-directory, but I would like to to put the root ABOVE several other repositories:

```
myproject/
├── .projectroot
├── client/
│   └── .git/
└── server/
    └── .git/
```

In other words I'd want the g:ctrlp_root_markers to be checked before all other markers (or having a separate such list)

**Comment by tankorsmash** [comment]
Are root markers and custom CtrlP mapping the only way to solve this still? I've got a tree that looks something like

```
FolderRoot
  \--> CodePWD (where my pwd is)
  \--> FolderIWantToAdd (folder I want ctrlp to include)
  \--> UnwantedFolder1 (one of dozens of folders I want to continue to ignore)
  \--> SecondUnwantedFolder (one of dozens of folders I want to continue to ignore)
  \--> Unwanted3rdFolder (one of dozens of folders I want to continue to ignore)
```

I can add a root_marker inside of `FolderRoot`, but that'll include  `UnwantedFolder1/2/3` as well. My current solution is to map `:CtrlP` and `:CtrlP ../FolderIWantToAdd`, but it would be nice if I could have both in one search.
