### ISSUE TITLE
Custom ignore for ctrlp

### ISSUE THREAD

**Issue by jgallen23** [kien/ctrlp.vim#58]
It would be nice to be able to set what files/directories to ignore without changing the wildignore setting.  I use both ctrlp and Nerd Tree, but I want them to ignore different things.  I don't want ctrlp to look inside the node_modules directory, but I want Nerd Tree to show the contents of that folder.

**Comment by lmartins** [comment]
Im still can't find a way to have ctrlp to ignore things like node_modules or jspm_packages in subfolders inside my git repo.

My repo has the following structure:

```
REPO
   - Project A
        - node_modules
   - Project B
        - node_modules
   - ...
```
No matter what I try, and I've tried every sample above, I always get results from those folders. 
Btw, im using Ag silver, not sure if it has any relation with this.
```
" The Silver Searcher
" http://robots.thoughtbot.com/faster-grepping-in-vim
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
```

Any tips?

**Comment by wagnerandrade** [comment]
Hi folks, I'm using the .gitignore itself to filter the useless files in ctrlp, like I described in superuser (https://superuser.com/questions/649714/can-i-get-the-vim-ctrlp-plugin-to-ignore-a-specific-folder-in-one-project/900794#900794):

---

To solve this with a file like `.gitignore` (based in the Nathan grep solution), I created a file named `.ctrlpignore` and put the patterns that should be ignored, separated by lines:

    node_modules/
    \.log$
    ...

And my ctrlp configuration:

    let g:ctrlp_user_command = 'find %s -type f | grep -v "`cat .ctrlpignore`"'

Maybe the `.gitignore` itself can be used to ignore the files in ctrlp, not needing to create a new file to do almost the same thing.

---

I hope it can help.

**Comment by cabouffard** [comment]
@lmartins From what I have read, custom_ignore is not working when using a custom finder.
You must create a ``.agignore`` in your home directory or in the project directory using the same syntax as a ``.gitignore``.

Please refer to the following link for a deeper explanation:
http://stackoverflow.com/a/18601066

**Comment by lmartins** [comment]
Thanks @cabouffard , I did managed to get it working as I wanted, not really sure how. Im just switched to Vim recently, still a lot to learn ;)

**Comment by lesterzone** [comment]
Thanks @spig this

```
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(\.(swp|ico|git|svn))$'
```

is working properly.

Amazing project!

**Comment by milushov** [comment]
my workaround
```
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files --exclude-standard -co |& egrep -v "\.(png|jpg|jpeg|gif)$|node_modules"']
```

**Comment by oompt** [comment]
I tried a bunch of these options. For me, the only one that seemed to work is 

``let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(\.(swp|ico|git|svn))$'``

from @spig

**Comment by paulosborne** [comment]
Solution posted by @blaenk works wonderfully :+1:

**Comment by dzlab** [comment]
this is awesome, I got huge perf boost by ignoring `target` folder in a scala project.

**Comment by daoanhnhat1995** [comment]
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(.(swp|ico|git|svn))$'
 works perfectly

**Comment by ain** [comment]
@hew's version worked best for me as well. Thanks a lot for sharing!

**Comment by nickrivadeneira** [comment]
Here's my `g:ctrlp_user_command`, which uses [the silver searcher](https://github.com/ggreer/the_silver_searcher) because it's so damn fast:

``` vimscript
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
endif
```

and then my `~/.agignore`:

```
node_modules
bower_components
git
```

It's working nicely for me.

**Comment by atcol** [comment]
I was using `ctrlp_user_command` which prevented `ctrlp_custom_ignore` from working. Removing the former fixed the latter for me!

**Comment by anpel** [comment]
I ended up doing what @wagnerandrade suggested, I just wrapped it in an if block to check if the .ctrlpignore file actually exists.

The section of my `.vimrc` looks like this:
```
if filereadable(".ctrlpignore")
    let g:ctrlp_user_command = 'find %s -type f | grep -v "`cat .ctrlpignore`"'
endif
```

**Comment by a-eid** [comment]
where do I add those commands? to `vimrc` directly?

**Comment by anpel** [comment]
@a-eid Yes, you can add these directly to your `.vimrc`.

**Comment by skgbanga** [comment]
@nickrivadeneira is there a way to make that case insensitive? I added `-I` option but that didn't help.

**Comment by nickrivadeneira** [comment]
@skgbanga I believe `-i` or `--ignore-case` only applies to selection, not rejection, of results in `ag`. So a case insensitive search for `foo` will match on `FOO`, but having `foo` in `.agignore` will not filter out `FOO`.

[This StackOverflow answer](https://stackoverflow.com/a/11116789/337903) hints at an option. If you want to filter out case insensitive `node_modules`, you could write the following:
```
[nN][oO][dD][eE]_[mM][oO][dD][uU][lL][eE][sS]
```
Awkward, but it should work. There may be other options. I believe `.agignore` follows the same rules as `.gitignore`, so searching on `.gitignore` syntax is gonna be your best starting point. If you find something, post back here, because I'm curious now :)

**Comment by timfeirg** [comment]
putting `git` in the custom ignore regex isn't a good idea, since ctrlp won't be able to collect anything from directories like `$GOPATH/src/github.com/...` or any directories with the substring `"git"` in their path.

**Comment by hiteshjoshi** [comment]
@spig's regex works.

**Comment by jedrekdomanski** [comment]
> Hi folks, I'm using the .gitignore itself to filter the useless files in ctrlp, the way I described in superuser (https://superuser.com/questions/649714/can-i-get-the-vim-ctrlp-plugin-to-ignore-a-specific-folder-in-one-project/900794#900794):
> 
> To solve this with a file like `.gitignore` (based in the Nathan grep solution), I created a file named `.ctrlpignore` and put the patterns that should be ignored, separated by lines:
> 
> ```
> node_modules/
> \.log$
> ...
> ```
> 
> And my ctrlp configuration:
> 
> ```
> let g:ctrlp_user_command = 'find %s -type f | grep -v "`cat .ctrlpignore`"'
> ```
> 
> Maybe the `.gitignore` itself can be used to ignore the files in ctrlp, not needing to create a new file to do almost the same thing.
> 
> I hope it can help.

This breaks the actual ctrlp behavior. If I have orders_controller.rb file and I type orderscontroller it finds only orders_controller_spec.rb and never finds the actual orders_controller.rb file.

The solution is this:
```
" Ignore some folders and files for CtrlP indexing
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.yardoc\|node_modules\|log\|tmp$',
  \ 'file': '\.so$\|\.dat$|\.DS_Store$'
  \ }
```
