### ISSUE TITLE
Issue of reoccuring re-initializing on Windows Mahcine.

### ISSUE THREAD

**Issue by llinfeng** [kien/ctrlp.vim#592]
Dear the community,

I am running gVim74 on a Windows machine and I have CtrlP.vim installed through Vundle. 

Every time I start a new session of gVime and press Ctrl+P, it would take more than 15 seconds to initialize. I resorted to solutions in Issue #395, but nothing changed after I had specified the following in my _vimrc. 

let g:ctrlp_cache_dir='C:\Users\Linfeng\Documents\Vim-document'

Any one could help me with this slow-boot issue? 

All the best, 
- Linfeng

**Comment by mooreniemi** [comment]
@llinfeng fixed same issue for me, ty
