### ISSUE TITLE
How to open file in new window/buffer

### ISSUE THREAD

**Issue by gilles-leblanc** [kien/ctrlp.vim#617]
Hi, 

I normally work in vim by opening multiple files at the same time and navigating with :n and :prev. Is there a way to have Ctrl-p open a file in a way that I can keep my current files open and do :n or :prev to navigate to the new file?

I am aware I can open a file in a new tab or a new split.

**Comment by IbnSaeed** [comment]
you can use ctrl-v for vertical split window and ctrl-x, or ctrl-s for horizontal split window

**Comment by dhilst** [comment]
Just a note, ctrl-s on terminal will lock the terminal, use ctrl-q to release. When using terminal use ctrl-x for horizontal split.
