### ISSUE TITLE
using ctrlp in Netrw populated the clipboard

### ISSUE THREAD

**Issue by ddaza** [kien/ctrlp.vim#648]
Hello this is an odd bug and I'm not even sure it is caused by ctrlp.
I usually open a new tab with netrw to navigate to a localfile.
```
:tabe .
```
If the file is not in the local folder I use ctrlp and open it in the same window. 
This works great, but for whatever reason the clipboard gets populated with junk from netrw.

Let me know if you need more info about this.

**Comment by qstrahl** [comment]
Pretty sure this is just due to netrw making use of the `+` or `*` register. Netrw has some quirky behaviour  =)

**Comment by RichardDooling** [comment]
As near as I can tell Netrw will do this if you have:

set clipboard=unnamed

in your .vimrc

However if you comment that out, then Vim will not use your system
clipboard (*, I think) unless you explicitly tell it to.

Rick

On Wed, Apr 22, 2015 at 2:16 PM, ddaza <notifications@github.com> wrote:

> Hello this is an odd bug and I'm not even sure it is caused by ctrlp.
> I usually open a new tab with netrw to navigate to a localfile.
>
> :tabe .
>
> If the file is not in the local folder I use ctrlp and open it in the same
> window.
> This works great, but for whatever reason the clipboard gets populated
> with junk from netrw.
>
> Let me know if you need more info about this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kien/ctrlp.vim/issues/648>.
>



-- 

rd

**Comment by ddaza** [comment]
I have my clipboard set to 'unnamedplus' which is basically the same. 
This is a desired behavior to access xterm's clipboard. 

I'm fairly new to vim's registers but if there is a way to stop this I can try it.

**Comment by qstrahl** [comment]
There's yer problem.

What you can do is not set `clipboard` like that, and instead any time you want to use your system's clipboard you can use the `"+` register (or the `"*` register for primary selection -- what you highlight with your mouse -- if you use linux)

**Comment by chopfitzroy** [comment]
Hey did anyone figure this out I have disabled any clipboard stuff and `netrw` is still filling the register of `../` .

Cheers,
Otis.
