### ISSUE TITLE
PCRE Issue

### ISSUE THREAD

**Issue by z3t0** [kien/ctrlp.vim#649]
Not sure what this means... Using Windows 8.1 64-bit and GVim. This error shows when I launch CtrlP.vim using `:CtrlP`

```
ERR: pcre_compile failed at position 3. Error: PCRE does not support \L, \l, \N{name}, \U, or \u
```

**Comment by z3t0** [comment]
Very odd because this is not a problem when using the command line vim instead of gvim

**Comment by z3t0** [comment]
No idea what solved it.. but it works all of a sudden. Thanks

**Comment by zhlinh** [comment]
I have the same problem now, and I want to know how to solve it?

**Comment by zhlinh** [comment]
Both Vim and gvim have this problem.So sad...

**Comment by qstrahl** [comment]
Try checking out `:help 'regexengine'`. That's the first thing that comes to mind.

**Comment by zhlinh** [comment]
Sorry, still have no idea how to fix it. I think maybe it's the regex problem too.

**Comment by amosbird** [comment]
Same problem here. I'm using Gvim on Windows 10.

**Comment by zhlinh** [comment]
See #665 , the same problem.
