### ISSUE TITLE
Can I cancel indexing?

### ISSUE THREAD

**Issue by nathanl** [kien/ctrlp.vim#655]
Sometimes, while working a normal project directory, I open another file in (say) `~`. I then invoke ctrlp. My intent is to look in the project directory, but it starts indexing the directory that file is in, locking up the UI until it completes.

Can I cancel the indexing process if I don't actually want to search in that directory?

**Comment by dmitriy5181** [comment]
In vim I see "press ctrl-c to abort" in status line on long indexing.

**Comment by nathanl** [comment]
Ah, that works unless I'm using MacVim in GUI mode (which I usually do), in which case it doesn't respond. Must be a MacVim bug.
