### ISSUE TITLE
Cannot use <c-s> to move to previous item

### ISSUE THREAD

**Issue by antoyo** [kien/ctrlp.vim#662]
Hello.
I'm trying to use `<c-s>` to select the previous item (instead of `<c-k>`).

Here is the config I used:

```
let g:ctrlp_prompt_mappings = {
      \ 'PrtSelectMove("j")':   ['<c-t>', '<down>'],
      \ 'PrtSelectMove("k")':   ['<c-s>', '<up>'],
      \ 'AcceptSelection("h")': ['<c-x>', '<c-cr>'],
      \ 'AcceptSelection("t")': [],
      \ }
```

`<c-t>` and `<up>` work fine but not `<c-s>`.
What is wrong with this config?
Thanks.

**Comment by Shougo** [comment]
https://unix.stackexchange.com/questions/137842/what-is-the-point-of-ctrl-s

**Comment by antoyo** [comment]
I've just noticed that `<c-s>` works fine in RXVT Unicode, but not in Mate Terminal (both of them running the fish shell). As I can use another terminal, this is not a problem for me and I believe this is not an issue of this plugin, so I close this issue.
