### ISSUE TITLE
Tags don't show up

### ISSUE THREAD

**Issue by sid-kap** [kien/ctrlp.vim#673]
if I press `:` and hit `<Tab>`, I see a list of all my ctags, but there is no tags tab on my Ctrl-P. I only see mru, files, and buf.
Do I need to enable tags in CtrlP somehow?

**Comment by sid-kap** [comment]
OK, I see that I needed to do
```
let g:ctrlp_extensions = ['tag']
```

Please add this to your readme or website!

**Comment by vsushkov** [comment]
@sid-kap https://github.com/kien/ctrlp.vim/issues/669
