### ISSUE TITLE
delay after selecting file

### ISSUE THREAD

**Issue by wwalker** [kien/ctrlp.vim#676]
I use ctrlp in a directory with 4500 files.  selection is snappy, I type 6 chars and the file I want is at the cursor.  :-)  I love CtrlP
Then I hit enter.  It's a full 3 seconds, up to 5 sometimes, before the buffer opens up.
If I exit vim and open the same file from "vim devops/eggheadjr/version.go" it opens near instantly (sub second).
Go back out, come in with "vim" and use CtrlP to select (snappy), hit enter... snooze ville.
I know I have a lot of files in the list, but it seems like the hard part is over when the delay comes in.
Wontfix is OK, just thought you might have an idea what the problem might be. 
Thanks again for CtrlP!!

**Comment by vsushkov** [comment]
@wwalker please, see https://github.com/kien/ctrlp.vim/issues/669

**Comment by wwalker** [comment]
Thanks!
