### ISSUE TITLE
>>>>>>>>>>>>>>>>>>>> GET SUPPORT FROM CTRLPVIM<<<<<<<<<<<<<<<<<<<<

### ISSUE THREAD

**Issue by wsdjeg** [kien/ctrlp.vim#682]
### GET SUPPORT FROM [CTRLPVIM](https://github.com/ctrlpvim/ctrlp.vim)
The Project Is Unmaintained Now,You Can Get Support From The Ctrlp Organization
and here is all the plugins worked base on ctrlp 
https://github.com/ctrlpvim/ctrlp.vim/wiki/ctrlp-plugins

**Comment by nowox** [comment]
I heard about (fuzzy-finder)[https://github.com/junegunn/fzf] which might be a nice alternative to ctrlp
