### ISSUE TITLE
weird characters in ctrlp search window

### ISSUE THREAD

**Issue by shangsunset** [kien/ctrlp.vim#701]
when using ctrlp in neovim, there are always weird character on the last line
![screen shot 2016-02-03 at 7 22 47 pm](https://cloud.githubusercontent.com/assets/3700269/12804071/a2ff0688-cabd-11e5-8167-9ee6dda7f6fa.png)

Tested in bash, zsh, fish. same result.

**Comment by rahmatismail** [comment]
have you solve this issue? I am experiencing similar issue
got random character too

**Comment by samuelbodin** [comment]
Same.... did you find a workaround yet?

**Comment by shangsunset** [comment]
I recommend using fzf and fzf.vim instead of ctrlp.vim.
