### ISSUE TITLE
Don't find file of working directory.

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [kien/ctrlp.vim#710]
Ubuntu 14.04 64 
vim version 7.4.52
issue：
When I use ctrlp find map.c file, I did not find the resulting files.But map.c file does exist in the working directory.

.vimrc configuration
let g:ctrlp_working_path_mode = 'ra'
set wildignore+=_/tmp/_,_.so,_.swp,*.zip     " MacOSX/Linux
let g:ctrlp_custom_ignore = '\v[\/].(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/].(git|hg|svn)$',
  \ 'file': '\v.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_user_command = 'find %s -type f'
![image](https://cloud.githubusercontent.com/assets/14014477/17454549/c7727fcc-5bcc-11e6-83b1-ee409daba505.png)

**Comment by ghost** [comment]
While open Ctrlp, press F5 to refresh. [link](https://stackoverflow.com/questions/8663829/vim-ctrlp-vim-plugin-how-to-rescan-files)

> <F5>

  - Refresh the match window and purge the cache for the current directory.
  - Remove deleted files from MRU list.
