### ISSUE TITLE
How to uninstall CtrlP from VIM?

### ISSUE THREAD

**Issue by LouisGameDev** [kien/ctrlp.vim#718]
I've googled, I've read the Readme. There seems o be no mention of how to remove this plugin from Vim. How do I cleanly remove this plugin from my vim installation?

**Comment by WhitleyStriber** [comment]
What operating system are you on? Did you see if CtrlP is installed through your OS's package manager? (apt-get, pacman, yum, etc.)

**Comment by LouisGameDev** [comment]
Thank you for your reply WhitleyStriber. I've figured out I could uninstall CtrlP by deleting the CtrlP.vim folder in my plugin manager's folder. Usually found somewhere in ~/.vim folder depending on the plugin manager.
