### ISSUE TITLE
CtrlPClearCache purge deleted files from file list but doesn't add new ones

### ISSUE THREAD

**Issue by oblitum** [kien/ctrlp.vim#725]
`:CtrlPClearCache` is not working for me to get new files listed, only for purging deleted ones, is that expected? I'm looking for a way to get new files listed without closing and opening Vim. It's the only way I know for CtrlP to start listing new files.

**Comment by ghost** [comment]
How did u end up making this work?

**Comment by oblitum** [comment]
@piotryordanov I've closed the issue b/c this repository URL is deprecated, I should have opened at https://github.com/ctrlpvim/ctrlp.vim. Shortly after I've moved away from ctrlp, I've solved by using FZF which I'm finding much better.

**Comment by ghost** [comment]
FZF is fantastic both for vim and outside of it. Thank you so much for the tip!
