### ISSUE TITLE
Ctrl + s hang ctrlp

### ISSUE THREAD

**Issue by xahon** [kien/ctrlp.vim#734]
If i press ctrl + s when ctrlp is opened vim becomes unresponding to any actions, but seems to be working. Cursor blinking, etc..

**Comment by maisieccino** [comment]
This is a general vim feature, not a ctrlp bug (essentially it's a "pause" command for vim). Ctrl+q should resume vim!

Detailed explanation: https://unix.stackexchange.com/a/72092
