### ISSUE TITLE
ctrlp + dirvish

### ISSUE THREAD

**Issue by bbtdev** [kien/ctrlp.vim#746]
Hello,
I'm no power user, so maybe this is a dumb request, but I do really love dirvish and I really love ctrlp. Is it possible to use ctrlp inside a dirvish window/buffer?

**Comment by dwayneyuen** [comment]
I know this is a bit old, but in case you were still looking for a solution, this works for me:

```vim
autocmd FileType dirvish nnoremap <buffer><silent> <c-p> :CtrlP<cr>
```
