### ISSUE TITLE
regexp looks broken (or am I missing someting here?)

### ISSUE THREAD

**Issue by Notaduck** [kien/ctrlp.vim#753]
I've added the line `let g:ctrlp_regexp = 1` to my init.vim (neovim) config, but for some odd reason I'm not able to search for anything while using a regular expression.  
  
Example:

As you can see I've the file `~/fail.md`
![screenshot 8](https://user-images.githubusercontent.com/9454064/41316445-adc697ae-6e92-11e8-9560-fc1f83efb4bb.jpg)
If i search for `*.md` then I will receive the message "no entries found" , am I missing something here or is it broken?
![screenshot 9](https://user-images.githubusercontent.com/9454064/41316444-ada0f904-6e92-11e8-9e1a-fc07ba8fdc87.jpg)

**Comment by spidey** [comment]
`*.md` is a not a regular expression, is a file glob pattern. You would search for `.*\.md` using regexp.

**Comment by Notaduck** [comment]
Ofc it isn't. Thanks
