### ISSUE TITLE
Files not addressable when freshly created using NERDTree

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [kien/ctrlp.vim#771]
#### What did I do
* Opened vim + NERDTree
* Created a new file using NERDTree
* Tried CtrlP to search for the file

#### What was expected to happen
The file should have been addressable with CtrlP

#### What actually happened
* File was not addressable
* File only became addressable after restarting vim

#### What environment I was using
* Ubuntu 18.04 LTS
* vim 8.0+
* NerdTree
* CtrlP

**Comment by Davids89** [comment]
Have you tried to refresh CtrlP with F5?

**Comment by L04DB4L4NC3R** [comment]
> Have you tried to refresh CtrlP with F5?

@Davids89 This works. Closing the issue now
