### ISSUE TITLE
Ctrlp won't open files in the default initial NERDTree window.

### ISSUE THREAD

**Issue by nicksergeant** [kien/ctrlp.vim#78]
When I open Vim, NERDTree opens a default window with the directory listings of where I've opened Vim:

```
vim .
```

When I use ctrlp for the first time, and I select a file, the file opens in a new window instead of the NERDTree window, forcing me to manually close the NERDTree window.

Is this a config issue with CtrlP or does this belong to NERDTree?

(thanks for the awesome plugin, btw!)

**Comment by blayz3r** [comment]
The option let g:ctrlp_dont_split = 'NERD' works until you change the mode then it doesn't close nerdtree again.Anyone else have this issue
