### ISSUE TITLE
g:ctrlp_custom_ignore not working?

### ISSUE THREAD

**Issue by cmeiklejohn** [kien/ctrlp.vim#79]
I've got the following in my .vimrc

``` vim
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$\|\.hg$\|\.svn$\|\.yardoc$',
  \ 'file': '\.exe$\|\.so$\|\.dat$'
  \ }
```

However, ctrl-p is still finding files such as .yardoc/objects/Thing.dat.  Am I misunderstanding how this is supposed to work?

**Comment by dtamez** [comment]
Yes!  :ClearAllCtrlPCaches finally got this working.

**Comment by andrewrk** [comment]
One thing to note, the `^` seemed not to match for me. So this didn't work:

``` vim
let g:ctrlp_custom_ignore = { 'dir': '^build$\|^node_modules$' }
```

but this did work:

``` vim
let g:ctrlp_custom_ignore = { 'dir': 'build$\|node_modules$' }
```

**Comment by jtr109** [comment]
It was the problem I meet too!
I copy all the vim script in README. So the line `ctrlp_user_command option` make the `ctrlp_custom_ignore` doesn't work!

**Comment by fakeharxy** [comment]
Ok so I'm pulling out my hair here - this is still happening to me. All above advice tried.

node_modules is only appearing for one project - but it's my main project - and it wasn't happening yesterday. Only things that have changed is that I have installed ultisnips and vim-snippets, and run ctrlpTag once, for the first time. I've deleted the cache, added `let g:ctrlp_custom_ignore = { 'dir': 'build$\|node_modules$' }` to my vimrc, and everything else on this list!

Any thoughts at all? It's driving me mad.

**Comment by fakeharxy** [comment]
Ok well I solved the above issue by adding `/node_modules/*` to by .gitignore. Still don't really understand what happened exactly but it's working.

**Comment by johnhaldson** [comment]
Just wanted to add, `node_modules` dir wouldn't be ignored for me unless i had active .git repo in the same dir.

**Comment by Tianyu00** [comment]
`ctrlp_custom_ignore` does not work for me (No matter I clear all caches or not). But `set wildignore` worked! (I am on MacOS.)
