### ISSUE TITLE
Navigating results with arrow keys turns on insert mode and inserts characters with `foot` terminal

### ISSUE THREAD

**Issue by nmschulte-aviture** [kien/ctrlp.vim#794]
I believe this issue is related to my choice of terminal.  It sets `TERM=foot`: https://codeberg.org/dnkl/foot.

After searching, trying to navigate the results list with the arrow keys, vim is switched to insert mode and A, B, C, or D characters are inserted, depending on the arrow.

Changing to e.g. `TERM=urxvt` seems to be a workaround.

How can I make this work without a workaround?

https://github.com/kien/ctrlp.vim/issues/209
https://github.com/kien/ctrlp.vim/issues/579

**Comment by erichamers** [comment]
Just if anyone runs into this issue and doesn't mind a quick fix, I'm on alacritty, putting `set term=xterm-256color` seems to do the trick.

**Comment by samhed** [comment]
I have the same issue despite having `term=xterm-256color` already.. This started happening after upgrading to vim version 8.2.4529 this morning.

**Comment by nsslh** [comment]
> I have the same issue despite having `term=xterm-256color` already.. This started happening after upgrading to vim version 8.2.4529 this morning.

Fixed in vim, see [issue](https://github.com/ctrlpvim/ctrlp.vim/issues/593#issuecomment-1069199328) in active fork.

**Comment by samhed** [comment]
Nice!

**Comment by nmschulte-aviture** [comment]
well, I don't know how I missed this; closing due to: https://github.com/kien/ctrlp.vim/commit/6b5fd4d7113840bf88f584e62988d7941c156d42
