### ISSUE TITLE
Feature Request: Close buffer via <c-something>

### ISSUE THREAD

**Issue by BonsaiDen** [kien/ctrlp.vim#93]
Would be really nice to have and it would be even better if it would closed all marked buffers. too.

btw: Thanks for the awesome plugin, I've used a mix of Command-T and FuzzyFinder but ctrlp just replaced both of them :)

**Comment by ezuk** [comment]
@rainerborene - very useful! Thank you.

**Comment by zQueal** [comment]
Came here for this. Ended up using this: https://github.com/j5shi/ctrlp_bdelete.vim

Works perfectly on Windows.
